import{loadGame,saveGame,resetSavedGame}from"./storage.js?v=0.5.4";
import{SYMBOLS,TEAM,WORLDS,EQUIPMENT,FIND_CATEGORIES,FACTIONS}from"./data.js?v=0.5.4";

const BUILD_VERSION="0.5.4";
const $=id=>document.getElementById(id);
const views=document.querySelectorAll(".view");
const glyphs=document.querySelectorAll(".glyph");
let selected=[],mission=null,probeUsed=false,probeOutcome=null,loadout=[],selectedWorldId="px761";

function freshGame(){return{version:BUILD_VERSION,energy:100,research:0,materials:0,equipmentSlots:1,completed:0,baseStatus:"Keine Expedition aktiv.",team:structuredClone(TEAM),worlds:structuredClone(WORLDS),equipment:structuredClone(EQUIPMENT),knownFactions:structuredClone(FACTIONS),unlockedWorldIds:["px761","px204","px118","px441"],surveyedWorldIds:[],visitedWorldIds:[],archive:[],finds:[],inventory:{fragment_threshold:0,threshold_eye:0},worldFlags:{px118Blocked:false,nonBreathableLogged:false,watchersObserved:false},projects:{threshold_eye:{id:"threshold_eye",name:"Schwellenrelikt rekonstruieren",status:"locked",requires:{fragment_threshold:3,research:6,materials:2},duration:2,remaining:0,resultItem:"threshold_eye"},expanded_loadout:{id:"expanded_loadout",name:"Zweiter Ausrüstungsslot",status:"locked",requires:{research:14,materials:8},duration:2,remaining:0,result:"equipment_slot"}}}}
function normalizeGame(saved){const base=freshGame();const g={...base,...saved};g.version=BUILD_VERSION;g.team=Array.isArray(saved.team)?saved.team:base.team;g.worlds=base.worlds;g.equipment=Array.isArray(saved.equipment)?saved.equipment:base.equipment;g.knownFactions={...base.knownFactions,...(saved.knownFactions||{})};g.inventory={...base.inventory,...(saved.inventory||{})};g.worldFlags={...base.worldFlags,...(saved.worldFlags||{})};g.projects={...base.projects,...(saved.projects||{})};g.unlockedWorldIds=Array.isArray(saved.unlockedWorldIds)&&saved.unlockedWorldIds.length?saved.unlockedWorldIds.map(id=>({p4x761:"px761",n7c204:"px204",k2m118:"px118"}[id]||id)):base.unlockedWorldIds;for(const id of base.unlockedWorldIds)if(!g.unlockedWorldIds.includes(id))g.unlockedWorldIds.push(id);g.surveyedWorldIds=Array.isArray(saved.surveyedWorldIds)?saved.surveyedWorldIds:[];g.visitedWorldIds=Array.isArray(saved.visitedWorldIds)?saved.visitedWorldIds:[];g.archive=Array.isArray(saved.archive)?saved.archive:[];g.finds=Array.isArray(saved.finds)?saved.finds:[];return g}
let game=loadGame(freshGame,normalizeGame);
selectedWorldId=game.unlockedWorldIds.find(id=>id!=="px441")||"px761";

const worldById=id=>game.worlds.find(w=>w.id===id);
const selectedWorld=()=>worldById(selectedWorldId);
const visited=id=>game.visitedWorldIds.includes(id);
const surveyed=id=>game.surveyedWorldIds.includes(id);
const hasLoadout=id=>loadout.includes(id);
const hasItem=id=>id==="threshold_eye"&&(game.inventory.threshold_eye||0)>0;
const rnd=(a,b)=>Math.floor(Math.random()*(b-a+1))+a;

function clone(o){return JSON.parse(JSON.stringify(o))}
function show(id){views.forEach(v=>v.classList.remove("active"));$(id).classList.add("active");window.scrollTo(0,0)}
function setGateStatus(text,state="idle"){$("gateStatus").textContent=text;$("gateIndicator").className="status-dot";if(state!=="idle")$("gateIndicator").classList.add(state)}
function displayName(w){return visited(w.id)?w.revealedName:w.unknownName}
function initSlots(address){$("addressSlots").innerHTML=address.map((s,i)=>`<div class="slot" data-slot="${i}">${SYMBOLS[s]}</div>`).join("")}
function update(){updateProjectLocks();$("energy").textContent=game.energy;$("research").textContent=game.research;$("materials").textContent=game.materials;$("slotsStat").textContent=game.equipmentSlots;$("baseStatus").textContent=game.baseStatus;$("equipmentCapacityText").textContent=`Aktuelle Einsatzkapazität: ${game.equipmentSlots} Modul${game.equipmentSlots>1?"e":""}.`;$("labValue").textContent=game.research;$("barFill").style.width=Math.min(100,game.research*7)+"%";renderAddressRegister();renderProjects();renderEquipmentArchive();renderFinds();renderFactions();renderArchive();renderTeam();game.version=BUILD_VERSION;saveGame(game)}
function renderTeam(){$("teamCards").innerHTML=game.team.map(t=>`<article><small>${t.role}</small><h3>${t.name}</h3><p>${t.traits}</p><p class="${t.health==="einsatzbereit"?"ok":"warning"}">Status: ${t.health}</p></article>`).join("")}
function renderAddressRegister(){let html=game.unlockedWorldIds.map(worldById).filter(Boolean).map(w=>{let title=visited(w.id)?`${w.code} · ${w.revealedName}`:`${w.code} · Unbekannte Zielwelt`;let state=visited(w.id)?"ERKUNDET":surveyed(w.id)?"SONDIERT":"UNBEKANNT";let meta=`Status: ${w.status}`;if(w.lockedText)meta+=` · ${w.lockedText}`;if(w.blocker&&visited(w.id))meta+=" · Blocker bekannt";return `<article class="address-entry"><small>${state}</small><h3>${title}</h3><p class="muted">${meta}</p><p class="mini">${w.address.map(s=>SYMBOLS[s]).join(" ")}</p></article>`}).join("");$("addressRegister").innerHTML=html}
function updateProjectLocks(){const p=game.projects.threshold_eye;if(p.status==="locked"&&(game.inventory.fragment_threshold||0)>=3)p.status="ready";const s=game.projects.expanded_loadout;if(s.status==="locked"&&game.research>=14&&game.materials>=8)s.status="ready"}
function projectHTML(p){const r=p.requires||{};const parts=[];if(r.fragment_threshold)parts.push(`Reliktfragmente ${game.inventory.fragment_threshold||0}/${r.fragment_threshold}`);if(r.research)parts.push(`Forschung ${game.research}/${r.research}`);if(r.materials)parts.push(`Material ${game.materials}/${r.materials}`);let label={locked:"gesperrt",ready:"bereit",done:"abgeschlossen"}[p.status]||p.status;if(p.status==="active")label=`Analyse läuft, noch ${p.remaining} Expedition${p.remaining===1?"":"en"}`;return `<article><h3>${p.name}</h3><p class="${p.status==="ready"?"ok":p.status==="active"?"warning":"muted"}">Status: ${label}</p><p class="mini">${parts.join(" · ")}</p>${p.status==="ready"?`<button data-project="${p.id}">Projekt starten</button>`:""}</article>`}
function renderProjects(){const html=Object.values(game.projects).map(projectHTML).join("");$("labProjects").innerHTML=html;$("projectPreview").innerHTML=html;document.querySelectorAll("[data-project]").forEach(b=>b.onclick=()=>startProject(b.dataset.project))}
function startProject(id){const p=game.projects[id];updateProjectLocks();if(!p||p.status!=="ready")return;const r=p.requires||{};if((game.inventory.fragment_threshold||0)<(r.fragment_threshold||0)||game.research<(r.research||0)||game.materials<(r.materials||0))return;if(r.fragment_threshold)game.inventory.fragment_threshold-=r.fragment_threshold;if(r.research)game.research-=r.research;if(r.materials)game.materials-=r.materials;p.status="active";p.remaining=p.duration||1;game.baseStatus=`Laborprojekt gestartet: ${p.name}.`;update()}
function tickProjects(){for(const p of Object.values(game.projects)){if(p.status==="active"){p.remaining=Math.max(0,p.remaining-1);if(p.remaining===0){p.status="done";if(p.resultItem==="threshold_eye")game.inventory.threshold_eye=(game.inventory.threshold_eye||0)+1;if(p.result==="equipment_slot")game.equipmentSlots=Math.max(game.equipmentSlots,2)}}}updateProjectLocks()}
function renderEquipmentArchive(){$("equipmentArchive").innerHTML=game.equipment.map(e=>`<article class="${e.unlocked?"":"locked"}"><small>${e.category}</small><h3>${e.name}</h3><p>${e.description}</p><div class="taglist">${e.tags.map(t=>`<span class="tag">${t}</span>`).join("")}</div><p class="${e.unlocked?"ok":"muted"}">${e.unlocked?"verfügbar":"noch nicht verfügbar"}</p></article>`).join("")}
function renderFinds(){if(!game.finds.length){$("findArchive").innerHTML="<article><p>Noch keine Funde dokumentiert.</p></article>";$("findPreview").textContent="Noch keine Funde dokumentiert.";return}const list=game.finds.slice().reverse();$("findArchive").innerHTML=list.map(f=>`<article><small>${FIND_CATEGORIES[f.category]||f.category}</small><h3>${f.name}</h3><p>${f.description}</p><p class="muted mini">Quelle: ${f.source}</p></article>`).join("");$("findPreview").innerHTML=list.slice(0,3).map(f=>`<p><b>${f.name}</b><br><span class="muted">${FIND_CATEGORIES[f.category]||f.category} · ${f.source}</span></p>`).join("")}
function renderFactions(){$("factionArchive").innerHTML=Object.values(game.knownFactions).map(f=>`<article class="${(f.known||0)>0?"":"locked"}"><small>${f.category}</small><h3>${(f.known||0)>0?f.name:"Unbekannte Signatur"}</h3><p>${(f.known||0)>0?f.description:"Noch keine bestätigten Begegnungen oder Daten."}</p><p class="muted mini">Wissensstand: ${f.known||0}</p></article>`).join("")}
function renderArchive(){$("archiveList").innerHTML=game.archive.length?game.archive.slice().reverse().map(r=>`<article class="report"><small>EINSATZAKTE ${r.no}</small><h3>${r.title}</h3><p class="report-meta">${r.planet} · ${r.outcome}</p><p>${r.summary}</p><div class="taglist">${(r.flags||[]).map(f=>`<span class="tag">${f}</span>`).join("")}</div><p class="warning"><b>Unvollständige Informationen:</b> ${r.info}</p><details><summary>Einsatzprotokoll öffnen</summary>${(r.log||[]).map(x=>`<p>${x}</p>`).join("")}</details></article>`).join(""):"<article><p>Noch keine Expedition abgeschlossen.</p></article>"}
function renderDestinations(){$("destinationList").innerHTML="";game.unlockedWorldIds.map(worldById).filter(Boolean).forEach(w=>{const b=document.createElement("button");b.className="destination-button"+(w.id===selectedWorldId?" active":"");b.innerHTML=`<strong>${w.code}</strong><span>${displayName(w)}</span><span>${w.lockedText||w.status}</span>`;b.onclick=()=>{selectedWorldId=w.id;resetGate(false)};$("destinationList").appendChild(b)})}
function renderDestinationInfo(){const w=selectedWorld();$("destinationCode").textContent=w.code;$("destinationName").textContent=displayName(w);let status=`Status: ${w.status}. `;status+=visited(w.id)?`Einsatzname bestätigt: ${w.revealedName}.`:surveyed(w.id)?"Sondendaten vorhanden. Einsatzname noch nicht bestätigt.":"Keine Einsatzdaten vorhanden.";if(w.lockedText)status+=` ${w.lockedText}`;$("destinationStatus").textContent=status;$("scanWorldCode").textContent=w.code;initSlots(w.address)}
function renderLoadout(){const cap=game.equipmentSlots;$("loadoutText").textContent=`Ausrüstungskapazität: ${cap}. Gewählte Module: ${loadout.length}/${cap}.`;const items=game.equipment.filter(e=>e.unlocked);$("loadoutList").innerHTML=items.map(e=>`<button class="module-button ${loadout.includes(e.id)?"active":""}" data-equip="${e.id}"><strong>${e.name}</strong><span>${e.category}</span><small>${e.description}</small></button>`).join("");document.querySelectorAll("[data-equip]").forEach(b=>b.onclick=()=>toggleEquip(b.dataset.equip))}
function toggleEquip(id){if(loadout.includes(id))loadout=loadout.filter(x=>x!==id);else{if(loadout.length>=game.equipmentSlots)loadout.shift();loadout.push(id)}renderLoadout()}
function resetProbeVisual(){const v=$("probeVisual");v.className="probe-visual scan-off";$("probeSignal").className="signal-label";$("probeSignal").textContent="KEIN SIGNAL";$("scanQuality").textContent="DATA 0%"}
function resetGate(changeWorld=true){selected=[];probeUsed=false;probeOutcome=null;loadout=[];if(changeWorld&&(!selectedWorldId||worldById(selectedWorldId)?.lockedText))selectedWorldId="px761";glyphs.forEach(g=>{g.classList.remove("selected","wrong");g.disabled=false});$("gate").classList.remove("open","dialing");setGateStatus("Gate inaktiv");$("probeData").innerHTML="<p>Noch keine Sondendaten vorhanden.</p>";$("probe").disabled=false;$("probe").textContent="Sonde senden · 5 Energie";$("start").disabled=true;renderDestinations();renderDestinationInfo();renderLoadout();resetProbeVisual()}
function lock(btn){const symbol=btn.dataset.symbol,addr=selectedWorld().address;if(symbol!==addr[selected.length]){btn.classList.add("wrong");setGateStatus(`Falsches Symbol · erwartet ${SYMBOLS[addr[selected.length]]}`,"error");setTimeout(()=>btn.classList.remove("wrong"),450);return}selected.push(symbol);btn.classList.add("selected");btn.disabled=true;document.querySelector(`[data-slot="${selected.length-1}"]`)?.classList.add("locked");setGateStatus(`Chevron ${selected.length} verriegelt`,"dialing");if(selected.length===addr.length)setTimeout(()=>{$("gate").classList.add("open");setGateStatus("Verbindung hergestellt","open");$("start").disabled=false},450)}
const wait=ms=>new Promise(r=>setTimeout(r,ms));async function autoDial(){resetGate(false);$("autoDial").disabled=true;for(const sym of selectedWorld().address){lock(document.querySelector(`[data-symbol="${sym}"]`));await wait(360)}$("autoDial").disabled=false}
function scanHTML(w){let lines=[`<p><b>Atmosphäre:</b> ${w.profile.environment}</p>`,`<p><b>Gelände:</b> ${w.profile.terrain}</p>`,`<p><b>Strukturen:</b> ${w.profile.structures}</p>`,`<p><b>Energie:</b> ${w.profile.energy}</p>`,`<p><b>Lebenszeichen:</b> ${w.profile.life}</p>`,`<p><b>Signatur:</b> ${w.profile.signature}</p>`];if(w.profile.environment.includes("nicht atembar")){game.worldFlags.nonBreathableLogged=true;lines.push(`<p class="warning"><b>Hinweis:</b> Diese Welt benötigt später Atmosphärenausrüstung.</p>`)}return lines.join("")}
function runProbe(){const w=selectedWorld();if(game.energy<5||probeUsed||w.lockedText)return;game.energy-=5;probeUsed=true;if(!game.surveyedWorldIds.includes(w.id))game.surveyedWorldIds.push(w.id);const roll=Math.random(),v=$("probeVisual");v.className=`probe-visual ${w.scanClass||""}`;$("scanWorldCode").textContent=w.code;if(roll<.18){probeOutcome="detected";v.classList.add("detected");$("probeSignal").className="signal-label alert";$("probeSignal").textContent="SIGNAL GESTÖRT";$("scanQuality").textContent="DATA 61%";$("probeData").innerHTML=scanHTML(w)+`<p class="dangerText"><b>Warnung:</b> Der Scan wurde möglicherweise bemerkt.</p>`}else if(roll<.38){probeOutcome="partial";v.classList.add("partial");$("probeSignal").className="signal-label partial";$("probeSignal").textContent="TEILSIGNAL";$("scanQuality").textContent="DATA 57%";$("probeData").innerHTML=scanHTML(w)+`<p class="warning"><b>Hinweis:</b> Telemetrie unvollständig.</p>`}else{probeOutcome="clean";$("probeSignal").className="signal-label live";$("probeSignal").textContent="LINK STABIL";$("scanQuality").textContent="DATA 96%";$("probeData").innerHTML=scanHTML(w)+`<p class="ok"><b>Status:</b> Sonde unentdeckt.</p>`}$("probe").disabled=true;$("probe").textContent="Sondendaten empfangen";renderDestinationInfo();update()}
function narration(t){$("story").insertAdjacentHTML("beforeend",`<div class="narration">${t}</div>`)}
function dialogue(n,t){$("story").insertAdjacentHTML("beforeend",`<div class="dialogue"><b>${n}</b><p>${t}</p></div>`)}
function clearStory(title,phase,status){$("sceneTitle").textContent=title;$("phase").textContent=phase;$("statusBadge").textContent=status;$("story").innerHTML=""}
function choices(list){$("choices").innerHTML="";list.forEach(c=>{const b=document.createElement("button");b.className="choice";b.innerHTML=`<strong>${c.title}</strong>`;b.onclick=c.action;$("choices").appendChild(b)})}
function startMission(){const w=selectedWorld();if(game.energy<10||selected.length!==w.address.length)return;if(w.lockedText){setGateStatus("Adresse nicht sicher anwählbar","error");return}game.energy-=10;mission={number:game.completed+1,worldId:w.id,planet:w.code,loadout:[...loadout],probeUsed,probeOutcome,result:null};$("missionNo").textContent=String(mission.number).padStart(3,"0");$("planetName").textContent=`${w.code} · ${displayName(w)}`;show("mission");opening();update()}
function equipLine(){if(hasLoadout("scanner"))return"Calder trägt den Feldscanner sichtbar am Unterarm.";if(hasLoadout("translator"))return"Jaxon hat das xenolinguistische Modul aktiv.";if(hasLoadout("impulse_shield"))return"Der mobile Impulsschutz hängt geladen am Tragegurt.";if(hasLoadout("breach_charge"))return"O'Dell hat eine Präzisionsladung eingepackt.";if(hasLoadout("medkit"))return"Das Expeditions-Medkit liegt griffbereit.";return"Das Team trägt Standardausrüstung ohne Spezialmodul."}
function opening(){const w=selectedWorld();clearStory("Erste Begehung","Akt 1: Ankunft","Status: Lage offen");$("return").classList.add("hidden");narration(`${probeUsed?"Die Sondendaten liegen vor.":"GC-1 betritt die Welt ohne vorherige Sondenaufklärung."} ${equipLine()} Diese Adresse hat noch keinen Einsatznamen. Für das Team ist sie zunächst nur ${w.code}.`);if(w.id==="px761"){dialogue("Captain Kim Calder","Die Struktur ist künstlich, aber teilweise im Gestein eingeschlossen.");dialogue("Dr. David Jaxon","Die Symbole wiederholen sich wie Warnhinweise.");dialogue("Colonel Jack O'Dell","Warnhinweise sind gut. Bedeutet meistens, dass jemand vorher Zeit zum Schreiben hatte.");choices([{title:"Die rechte Fassung untersuchen",action:()=>resolve(hasLoadout("scanner")?"px761Fragment":"px761Wrong")},{title:"Die Symbolreihen deuten",action:()=>resolve(hasLoadout("translator")?"px761Translate":"px761Guess")},{title:"Den Nebenraum öffnen",action:()=>resolve(hasLoadout("breach_charge")?"px761Breach":"px761Force")}])}else if(w.id==="px204"){dialogue("Captain Kim Calder","Mehrere Wärmeschatten bewegen sich parallel zum Gate. Das wirkt organisiert.");dialogue("Tae'Khan","Sie testen unsere Reaktion.");dialogue("Colonel Jack O'Dell","Dann sollten wir möglichst nicht wie ein Testfehler aussehen.");game.knownFactions.temple_guard.known=(game.knownFactions.temple_guard.known||0)+1;choices([{title:"Die Waffen sichtbar senken",action:()=>resolve("px204Diplomacy")},{title:"Das beschädigte Fluggerät untersuchen",action:()=>resolve(hasLoadout("scanner")?"px204Ship":"px204ShipBlind")},{title:"Tae'Khan vortreten lassen",action:()=>resolve("px204Taekhan")}])}else if(w.id==="px118"){dialogue("Captain Kim Calder","Der Tiefenzugang reagiert auf ein Identifikationsmuster.");dialogue("Dr. David Jaxon","Die Form erinnert an die Fragmente aus den anderen Ruinen.");dialogue("Colonel Jack O'Dell","Eine Tür mit Zubehörpflicht. Wunderbar.");if(!hasItem("threshold_eye"))choices([{title:"Tiefenzugang untersuchen",action:()=>resolve("px118Blocked")},{title:"Oberflächenstruktur kartieren",action:()=>resolve("px118Surface")},{title:"Rückzug anordnen",action:()=>resolve("retreat")}]);else choices([{title:"Das Schwellenrelikt einsetzen",action:()=>resolve("px118Open")},{title:"Nur Daten extrahieren",action:()=>resolve("core")},{title:"Rückzug anordnen",action:()=>resolve("retreat")}])}else if(w.id==="px392"){dialogue("Captain Kim Calder","Die Ruinen werden in wenigen Minuten wieder überflutet.");dialogue("Dr. David Jaxon","Das Wasser ist Teil der Anlage. Kein Schaden, sondern Mechanismus.");dialogue("Colonel Jack O'Dell","Ich werde von einer Pfütze unter Zeitdruck gesetzt.");choices([{title:"Den Splitter bergen",action:()=>resolve(hasLoadout("impulse_shield")?"px392FragmentSafe":"px392FragmentRisk")},{title:"Den Flutmechanismus beobachten",action:()=>resolve("tide")},{title:"Sofort zurück zum Gate",action:()=>resolve("retreat")}])}}
function addFind(f){game.finds.push({...f,at:new Date().toISOString()});if(f.inventoryKey)game.inventory[f.inventoryKey]=(game.inventory[f.inventoryKey]||0)+(f.amount||1)}
function reveal(w){if(!game.visitedWorldIds.includes(w.id))game.visitedWorldIds.push(w.id)}
function unlock(id){if(!game.unlockedWorldIds.includes(id))game.unlockedWorldIds.push(id)}
function resolve(kind){const w=selectedWorld();reveal(w);let title="Einsatz abgeschlossen",outcome="Teilerfolg",summary="GC-1 kehrte mit verwertbaren Daten zurück.",info="Mehrere Zusammenhänge bleiben ungeklärt.",flags=["Daten gesichert"],research=2,mat=0,lines=[],find=null;
if(kind==="px761Fragment"){title="Erstes Reliktfragment geborgen";outcome="Erfolg";summary="GC-1 fand ein Bruchstück einer runden Schwellenstruktur.";info="Das Fragment gehört offenbar zu einem größeren Mechanismus.";flags=["Reliktfragment","Scanner genutzt"];research=4;mat=2;unlock("px392");find={name:"Kheprischer Schwellen-Splitter",category:"relic_fragment",inventoryKey:"fragment_threshold",amount:1,source:w.code,description:"Ein gebrochenes Reliktstück mit leitfähigen Symboladern."};lines=[["Captain Kim Calder","Der Scanner hat den Hohlraum bestätigt."],["Dr. David Jaxon","Die Bruchlinien sind zu regelmäßig. Das ist nur ein Teil."],["Colonel Jack O'Dell","Natürlich. Ein Schlüssel als Sammelaufgabe."]]}
else if(kind==="px761Wrong"){title="Fassung beschädigt";outcome="Verpasste Chance";summary="Das Team öffnete die falsche Platte und verlor den Zugang zum inneren Hohlraum.";info="Ein Reliktfragment blieb unerreichbar.";flags=["Fehlentscheidung","kein Fund"];research=1;lines=[["Captain Kim Calder","Die Fassung ist eingerastet."],["Colonel Jack O'Dell","Dann war das offiziell ein Lernmoment. Ein teurer."]]}
else if(kind==="px761Translate"){title="Warntext entschlüsselt";outcome="Kultureller Erfolg";summary="Jaxon rekonstruierte eine Warnung über drei getrennte Trägerstücke.";info="Der Text erwähnt eine Tür unter Eis.";flags=["Übersetzung","PX-118 Hinweis"];research=5;unlock("px392");find={name:"Warnung der drei Träger",category:"cultural",source:w.code,description:"Eine rekonstruierte Inschrift über drei getrennte Reliktträger."};lines=[["Dr. David Jaxon","Drei Träger öffnen die Schwelle. Einer allein ruft nur die Wächter."],["Colonel Jack O'Dell","Keine halben Gottestüren öffnen. Notiert."]]}
else if(kind==="px761Guess"){title="Symbolfolge fehlgedeutet";outcome="Teilerfolg";summary="Die Symbolreihen wurden nur grob dokumentiert.";info="Ohne Übersetzungsmodul bleibt die Warnung unvollständig.";flags=["Unvollständige Übersetzung"];research=2;lines=[["Dr. David Jaxon","Ich kann es eingrenzen, aber nicht sicher übersetzen."]]}
else if(kind==="px761Breach"){title="Nebenraum geöffnet";outcome="Materialfund";summary="Die Präzisionsladung öffnete einen Nebenraum mit alter Technik.";info="Die zentrale Fassung blieb unberührt.";flags=["Technologiekomponente","Zugang geöffnet"];research=2;mat=6;find={name:"Isolierte Resonanzspule",category:"technology",source:w.code,description:"Eine intakte Spule aus einem alten Kontrollsystem."};lines=[["Colonel Jack O'Dell","Präzise genug."],["Dr. David Jaxon","Und ein Wandbild ist jetzt Geschichte."]]}
else if(kind==="px761Force"){title="Zugang blockiert";outcome="Verpasste Chance";summary="Ohne passendes Werkzeug blockierte der Nebenraum endgültig.";info="Ein technischer Fund blieb unerreichbar.";flags=["Kein passendes Modul"];research=1;lines=[["Captain Kim Calder","Wenn wir das erzwingen, bricht die Führungsschiene."]]}
else if(kind==="px204Diplomacy"){title="Kontakt im Basalttal";outcome="Diplomatischer Erfolg";summary="GC-1 vermied eine Eskalation mit einer bewaffneten Wächtergruppe.";info="Die Wächter scheinen nicht unabhängig zu handeln.";flags=["Fraktionskontakt","Tempelkrieger"];research=4;mat=1;unlock("px392");game.worldFlags.watchersObserved=true;find={name:"Zeichen der Tempelkrieger",category:"faction_data",source:w.code,description:"Ein visuelles Fraktionsmerkmal der imperialen Tempelkrieger."};lines=[["Dr. David Jaxon","Sie reagieren auf Zeichen, nicht auf Sprache."],["Colonel Jack O'Dell","Ich liebe Religionen mit Dienstplan."]]}
else if(kind==="px204Ship"){title="Navigationskern extrahiert";outcome="Technischer Erfolg";summary="Calder sicherte Koordinaten aus einem beschädigten Fluggerät.";info="Eine Route verweist auf eine instabile Flutwelt.";flags=["Navigationskern","PX-392"];research=5;mat=3;unlock("px392");find={name:"Schwarzer Navigationskern",category:"technology",source:w.code,description:"Ein beschädigter Navigationskern mit mehreren Gate-Fragmentadressen."};lines=[["Captain Kim Calder","PX-392 taucht mehrfach auf. Kein Name, nur eine Warnsequenz."],["Colonel Jack O'Dell","Eine Warnung ist fast eine Einladung. Nur ehrlicher."]]}
else if(kind==="px204ShipBlind"){title="Fluggerät alarmiert";outcome="Gefahr";summary="Ohne Scanner löste das Team eine Sicherungsroutine aus und musste ausweichen.";info="Der Navigationskern blieb teilweise verschlüsselt.";flags=["Alarm","Teilinformationen"];research=2;mat=1;unlock("px392");lines=[["Captain Kim Calder","Ich hätte vorher gern gesehen, was ich berühre."]]}
else if(kind==="px204Taekhan"){title="Tae'Khans Zeichen";outcome="Storyfolge";summary="Die Wächter erkannten ein altes Zeichen auf Tae'Khans Ausrüstung.";info="Tae'Khans Vergangenheit hat Verbindung zu dieser Kaste.";flags=["Tae'Khan erkannt"];research=3;lines=[["Tae'Khan","Ich trug dieses Zeichen, bevor ich frei war."],["Colonel Jack O'Dell","Zu spät. Sie schreiben innerlich schon einen Bericht."]]}
else if(kind==="px118Blocked"){title="Versiegelter Tiefenzugang";outcome="Blocker bestätigt";summary="Der Tiefenzugang verlangt ein rekonstruiertes Relikt.";info="Es fehlen drei passende Reliktfragmente.";flags=["Blocker","Schwellenrelikt"];research=3;game.worldFlags.px118Blocked=true;find={name:"Schema der Schwellentür",category:"research_data",source:w.code,description:"Messdaten einer Tür, die auf ein zusammengesetztes Relikt reagiert."};lines=[["Captain Kim Calder","Das System ist vollständig. Nur der Schlüssel fehlt."],["Colonel Jack O'Dell","Dann finden wir den Schlüssel."]]}
else if(kind==="px118Surface"){title="Oberflächenstruktur kartiert";outcome="Teilerfolg";summary="GC-1 bestätigte weitere Daten der Eisstruktur.";info="Der Hauptzugang bleibt verschlossen.";flags=["Kartierung","Blocker"];research=3;mat=1;lines=[["Dr. David Jaxon","Der Ort wartet nicht auf uns. Er wartet auf etwas, das wir tragen sollen."]]}
else if(kind==="px118Open"){title="Schwelle geöffnet";outcome="Großer Erfolg";summary="Das rekonstruierte Schwellenrelikt öffnete den Tiefenzugang unter PX-118.";info="Die Archivdaten nennen Orte, die noch nicht im Adressregister stehen.";flags=["Tiefenarchiv","Relikt eingesetzt"];research=8;mat=2;find={name:"Archivkern der Eisstruktur",category:"artifact",source:w.code,description:"Ein stabiler Datenkern aus einer unterirdischen Archivschicht."};lines=[["Captain Kim Calder","Die Tür akzeptiert das Relikt."],["Dr. David Jaxon","Nicht als Schlüssel. Als Ausweis."]]}
else if(kind==="core"){title="Datenkern gesichert";outcome="Teilerfolg";summary="GC-1 sicherte Daten, ohne die Hauptkammer vollständig zu öffnen.";info="Die Hauptkammer bleibt verschlossen.";flags=["Datenkern"];research=4;mat=1;lines=[["Captain Kim Calder","Genug Daten für eine neue Analyse."]]}
else if(kind==="px392FragmentSafe"){title="Reliktfragment geborgen";outcome="Erfolg";summary="Der Impulsschutz stabilisierte die Flutenergie lange genug für eine sichere Bergung.";info="Alle Fragmente können später im Labor rekonstruiert werden.";flags=["Reliktfragment","Laborprojekt möglich"];research=4;mat=2;find={name:"Flutgebundener Schwellen-Splitter",category:"relic_fragment",inventoryKey:"fragment_threshold",amount:1,source:w.code,description:"Ein Reliktfragment, das nur während einer Flutphase erreichbar war."};lines=[["Captain Kim Calder","Der Impulsschutz hält."],["Colonel Jack O'Dell","Dann ab nach Hause, bevor das Meer Einspruch erhebt."]]}
else if(kind==="px392FragmentRisk"){title="Fragment verloren";outcome="Verpasste Chance";summary="Das Fragment wurde erreicht, aber eine Energieentladung riss es in die Flut zurück.";info="Mit besserem Schutz könnte eine Bergung möglich sein.";flags=["Fehlende Ausrüstung","Fragment verloren"];research=2;lines=[["Captain Kim Calder","Die Entladung war vorhersehbar. Nur nicht sichtbar."]]}
else if(kind==="tide"){title="Flutmechanismus verstanden";outcome="Analyseerfolg";summary="GC-1 erkannte, dass die Ruinen über Wasserstand und Gate-Energie gesteuert werden.";info="Ein Fragment erscheint nur während einer kurzen Resonanzphase.";flags=["Flutmechanismus"];research=5;lines=[["Dr. David Jaxon","Das Meer ist kein Hindernis. Es ist der Taktgeber."]]}
else if(kind==="retreat"){title="Geordneter Rückzug";outcome="Rückzug";summary="GC-1 brach die Untersuchung ab und sicherte die bisherigen Daten.";info="Der Hauptbereich blieb unerforscht.";flags=["Mission abgebrochen"];research=1;lines=[["Dr. David Jaxon","Wir werden zurückkommen müssen."],["Colonel Jack O'Dell","Dann kommen wir zurück. Mit besserem Plan."]]}
if(find)addFind(find);game.research+=research;game.materials+=mat;game.baseStatus=`Expedition ${String(mission.number).padStart(3,"0")} abgeschlossen: ${outcome}.`;mission.result={title,outcome,summary,info,flags,text:`Die Expedition auf ${w.code} endet mit ${outcome}. Forschung +${research}, Material +${mat}.`,lines};clearStory(title,"Abschluss","Status: Rückkehr möglich");narration(mission.result.text);lines.forEach(x=>dialogue(x[0],x[1]));$("choices").innerHTML="";$("return").classList.remove("hidden");update()}
function returnBase(){const r=mission.result;game.archive.push({no:String(mission.number).padStart(3,"0"),planet:mission.planet,title:r.title,outcome:r.outcome,summary:r.summary,info:r.info,flags:r.flags,log:[...$("story").children].map(x=>x.textContent.trim())});game.completed++;tickProjects();mission=null;resetGate();update();show("base")}
document.querySelectorAll("[data-view]").forEach(b=>b.onclick=()=>show(b.dataset.view));
glyphs.forEach(b=>b.onclick=()=>lock(b));
$("prepare").onclick=()=>{resetGate();show("gateView")};
$("autoDial").onclick=autoDial;
$("probe").onclick=runProbe;
$("start").onclick=startMission;
$("return").onclick=returnBase;
$("reset").onclick=()=>{if(confirm("Den gesamten Spielstand einschließlich Einsatzarchiv löschen?")){resetSavedGame();game=freshGame();selectedWorldId="px761";mission=null;resetGate();update();show("base")}};
resetGate();update();
